### PR TITLE
upd: data to latest preview

### PR DESCRIPTION
**Pull request by NguyenDuck**
- [x] Script module version
- [x] Released the `minecraft:enchantable` item component out of experimental
- [x] Deprecated `minecraft:mining_speed` item component

### CODE REVIEW

**Comment by ExDrill** [comment]
I have some changes ready to go, could you make this branch modifiable?

**Comment by outercloudstudio** [comment]
When this pr is done make sure to request review

**Comment by ThomasOrs** [comment]
Should this be pulled into the other 1.20.30 PR? 1.20.40 previews have started so we are in no more change land for 1.20.30

**Comment by NguyenDuck** [comment]
Moved to #53

**Pull request closed without merging**
