### PR TITLE
Update tree_feature.json

### PR DESCRIPTION
**Pull request by KekeCreations**
Fixed typos and general mistakes

### CODE REVIEW

**Comment by Joelant05** [comment]
Do the "block_reference" -> "decoration_block" changes apply to just format versions 1.19.0+ or do they apply before then as well? @KekeCreations

**Comment by KekeCreations** [comment]
> Do the "block_reference" -> "decoration_block" changes apply to just format versions 1.19.0+ or do they apply before then as well? @KekeCreations

They apply before then aswell

**Comment by KekeCreations** [comment]
> > Do the "block_reference" -> "decoration_block" changes apply to just format versions 1.19.0+ or do they apply before then as well? @KekeCreations
> 
> They apply before then aswell

ill change the others aswell

**Review by Joelant05 — APPROVED** [review]
Awesome, looks good now, thanks!

**Pull request merged**
