### PR TITLE
Update to 1.20.40.23 

### PR DESCRIPTION
**Pull request by ExDrill**
* Updated item components
* Added camera presets
* Updated scripting modules
* Updated gamerules
* Add /inputpermission
* Re-sorted entity filters to be in alphabetical order

### CODE REVIEW

**Comment by ExDrill** [comment]
@outercloudstudio Could you try and tackle the camera command?

**Comment by NguyenDuck** [comment]
@ExDrill I'm not so sure about this part, can you do it?
- [ ] Exposed new data parameter `can_spread_on_fire` for the `minecraft:behavior.melee_attack` entity component to specify if the mob should set its target on fire when attacking if the attacking mob is on fire

**Comment by ExDrill** [comment]
Oh yeah, that's right! Thanks for reminding me.

**Comment by outercloudstudio** [comment]
> @outercloudstudio Could you try and tackle the camera command?

Yeah I'll take a look. I'll need you to help me with how the command works though since I've never used it.

**Comment by NguyenDuck** [comment]
- [ ] Allow single value parsing for `minecraft:icon` item component
 - [ ] New entity component `minecraft:dash`
 - [ ] Deprecated `block_property`, `has_block_property` favor of `block_state`, `has_block_state` - 1.20.40 ( Molang )

**Comment by ExDrill** [comment]
The molang changes are currently already in, and `minecraft:dash` isn't a new component, it's usage is just allowed outside the camel's runtime identifier. Thanks for reminding me about the `minecraft:icon` changes, though!

**Comment by outercloudstudio** [comment]
If this is complete, request a review so we can get bridge updated to latest data asap.

**Comment by ThomasOrs** [comment]
Didn't block property get renamed to block state in this update?

**Comment by ExDrill** [comment]
I'm pretty sure the changes rolled around in 1.20.20/1.20.30. The date update for those are already implemented, the changelogs just never stated them up until now.

**Comment by outercloudstudio** [comment]
@ExDrill tells me that the pr is ready to go so I'm going to review this tomorrow.

**Review by outercloudstudio — CHANGES_REQUESTED** [review]
A few changes are missing:
> Allow single value parsing for "minecraft:icon" item component

Change deprecation messages in the following files to match the standard:
- packages\minecraftBedrock\schema\entity\v1.20.40\behaviors\behavior.feeling_happy.json
- packages\minecraftBedrock\schema\entity\v1.20.40\behaviors\behavior.rising.json
- packages\minecraftBedrock\schema\entity\v1.20.40\behaviors\behavior.scenting.json
- packages\minecraftBedrock\schema\item\v1.20.20\components\animates_in_toolbar.json
- packages\minecraftBedrock\schema\item\v1.20.30\components\mining_speed.json
- packages\minecraftBedrock\schema\item\v1.20.40\components\on_use_on.json
- packages\minecraftBedrock\schema\item\v1.20.40\components\on_use.json
- packages\minecraftBedrock\schema\item\v1.20.40\components\weapon.json

Otherwise, all looks good to me

**Review by outercloudstudio — APPROVED** [review]

**Comment by sweetBR** [comment]
still can't see wereable and new item component stuff in 2.6.2, its a problem on my end or the update didnt cover these 1.20.30 stable stuff ?

**Comment by outercloudstudio** [comment]
The update should have covered these. What is your project target format version on?

**Comment by sweetBR** [comment]
> The update should have covered these. What is your project target format version on? @sweetBR

i did a test project with 1.20.40 target for testing, i'll send a test video

image


https://github.com/bridge-core/editor-packages/assets/8238573/5e9ef6d8-55d5-4393-9c2e-4f6bf1bc9158

**Comment by outercloudstudio** [comment]
I'll take a look today and see what the issue is.

**Comment by outercloudstudio** [comment]
@sweetBR Try setting your item format version to 1.20.40

**Comment by sweetBR** [comment]
> @sweetBR Try setting your item format version to 1.20.40

Worked ! Thanks a lot, usually the new updates copy the input of the project in the manifest

**Pull request merged**
