### PR TITLE
Update to latest preview (1.20.20.22)

### PR DESCRIPTION
**Pull request by ExDrill**
What's currently in:
* All data from 1.20.20.21 should now be implemented
* Released `minecraft:wearable` out of experimental
* Released `minecraft:digger` out of experimental
* Deprecated `on_dig` parameter in `minecraft:digger` on format versions higher than 1.20.20
* Update scripting modules to 1.20.20.22

What's left:
* Release features and feature rules out of experimental. This means every single feature type EXCEPT for `minecraft:conditional_list`, `minecraft:beards_and_shavers`, `minecraft:scan_surface`, `minecraft:rect_layout` and `minecraft:sculk_patch_feature`
* /camera is out of experimental.

### CODE REVIEW

**Comment by NguyenDuck** [comment]
I think we need add module `@minecraft/vanilla-data` to reference `MinecraftTypes` soon!

Block traits release out of experimental ( 1.20.20+ )

As you mentioned above, we need to modify versions of item schema like block schema later version inherits previous version or edit based on previous version, parts in Holiday Creator Features have can be used in the main.json of each version and not in the global main.json

**Comment by outercloudstudio** [comment]
I mistakenly thought the new preview was 1.20.21 but the latest commit should fix that.

**Review by NguyenDuck — COMMENTED** [review]
Then, now you know why i request removed format_on_save setting 👍

**Comment by outercloudstudio** [comment]
> Then, now you know why i request removed format_on_save setting 👍 
> Whatever, never mind

Are you referring to the way the json formats on save? I'll have to configure that so it's consistent across our devices.

**Review by ThomasOrs — APPROVED** [review]

**Pull request merged**
