### PR TITLE
Update snowball and sword item presets

### PR DESCRIPTION
**Pull request by Chikorita-Lover**

### CODE REVIEW

**Review by Joelant05 — CHANGES_REQUESTED** [review]
Changes to the snowball preset look good.
With the sword preset, you've added the item_texture.json creation to the manifest, however this is already handled in the `itemImages.js` preset script; once that is removed I should be ok to merge this
Thanks!

**Comment by Chikorita-Lover** [comment]
Gotcha, I'll get to that as soon as possible!

**Comment by Chikorita-Lover** [comment]
I forgot to do this, so it's a bit later than I could've done it. But it should be done and ready to merge!

**Review by Joelant05 — APPROVED** [review]
Looks great now thanks!

**Pull request merged**
