### PR TITLE
Update to 1.20.50.22

### PR DESCRIPTION
**Pull request by ExDrill**
* Added `minecraft:use_modifiers`
* Updated `minecraft:tags`
* Deprecated `minecraft:use_duration` and `minecraft:chargeable`
* Updated 1.20.50 script modules to latest preview.
* Updated 1.20.40 and 1.20.30 script modules to use stable releases.

* `minecraft:mining_speed` is now properly deprecated on format versions 1.20.30 and above.
* Fixed an issue with `minecraft:on_use` on format version 1.20.40

### CODE REVIEW

**Review by outercloudstudio — CHANGES_REQUESTED** [review]
I believe some new identifiers for items and blocks were added in this update so the vanilla data will need to be scraped again. Otherwise this looks good to me.

**Comment by ExDrill** [comment]
Alright, I ran the script, everything should be ready now!

**Review by outercloudstudio — APPROVED** [review]
LGTM

**Review by gabrielbellune — COMMENTED** [review]
Minecraft dans beta aperçu 1.20.50.23,
je t'envoyé la liste de beta preview 1.20.50.23

new items
copper nugget - copper horn - copper armor - ruby -saphir

la fonctionnalisé Education Edition

item error - new skin npc

java parity

debug stick added -bundle added - data commands added 

mob lost

firefly - frog - willdfire  - great hunger - copper golem and tuff golem

interface 

offhand items - custom bottons colors

more...

**Comment by outercloudstudio** [comment]
If you have an issue, please open a new one.

**Pull request merged**
